---
- name: put thrift server eye config file
  template: src=hbase/thrift.rb dest=/etc/eye/thrift-server-{{ env_name }}.rb owner=root group=root mode=0644

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  sudo: yes

- name: restart when hbase-site.xml changed
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye restart thrift-server"
  when: hbase_site_xml is defined and hbase_site_xml.changed
